name: Pipeline

on:
  push:
    branches:
      - develop
      - acceptance
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - develop
      - acceptance
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/setup-project.yml
    with:
      name: "Main Workflow"
      run-tests: true